#Use allele count of 1 to identify Private alleles in entire data set:

#To do this within populations this must be computed manually on the dataset filtered by population
#Sample IDs for population based filtering are to be generated fron the EXCEL file provided by
#1000 Genomes Project, saved as a filtered .txt file and then imported into R as a DataFrame

#Identify population private alleles by comparing alleles from one population of interest vs.  the union of all other populations:

#Import all of the SVBED files generated by "All ROIs Gen"

